### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by RJPvT** [kid1194/frappe-list-unassign-from#1]
Hi

I'm getting the following error on install 👍 

Building frappe_list_unassign_from assets...

EMPTY_BUNDLE : Generated an empty bundle
✔ Built js/unassign_from.js

*** Error compiling '/home/frappe/frappe-bench/apps/frappe_list_unassign_from/frappe_list_unassign_from/config/desktop.py'...
Sorry: IndentationError: expected an indented block (desktop.py, line 4)

no menu is shown

**Comment by kid1194** [comment]
@RJPvT Thank you so much for reporting this..

I have updated the plugin. Please give it another try and let me know if there is any problem..

Best regards..

**Comment by RJPvT** [comment]
Hi @kid1194 still not seeing the button in the menu. the errors are gone but i still get a : 

Building frappe_list_unassign_from assets...

EMPTY_BUNDLE : Generated an empty bundle
✔ Built js/unassign_from.js
✨  Done in 0.002s
Done in 34.17s.
Compiling Python files...
